# <p style="background-color:lightgray; font-family:verdana; font-size:250%; text-align:center; border-radius: 15px 20px;">🟠Numpy and Pandas🟠</p>

# <p style="border-radius:10px; border:#DEB887 solid; padding:25px; background-color: #FFFAF0; font-size:100%;color:#52017A;text-align:center;"> Numpy  </p>

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 What is Numpy and why should i use Numpy ?</font></h3>

### Numpy is the abbreviation for Numerical Python. It is a library that is developed for mathematics and statistics operations. Unlike lists, numpy holds data with a fixed type, allowing for efficient operations. It provides the capability to perform more operations with less effort.

### There is two important reasons for using Numpy, which is;

* Speed, it holds fixed data so it is fast.
* It easily enables high-level operations.

In [1]:
#we are importing numpy as np, so in next parts when we are using the library, our shortcut will be np
import numpy as np

In [2]:
#in a pyhtonic way, for multiplication of two different list, we have to make a for loops and long codes like below;
a = [1,2,3,4]
b = [2,3,4,5] 
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
ab

[2, 6, 12, 20]

In [3]:
#but as you can see, with numpy we can do it waaaaay tooo more faster..
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a * b

array([ 2,  6, 12, 20])

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 How can i make Numpy array?</font></h3>

In [4]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
#We called the zeros method from the numpy library, which creates the specified number of zeros inside the method.
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#Method used for generating random numbers
np.random.randint(0, 10, size= 10)      #We selected a random number within a specific range

array([9, 7, 0, 4, 8, 1, 2, 8, 0, 8])

In [7]:
np.random.normal(10,4,(3,4))  #We generated a random number of size 3x4 with a mean of 10 and a standard deviation of 4.

array([[ 3.16606785,  9.21082014, 12.94917235, 13.30876884],
       [16.49395405,  9.35030388, 16.22871289, 12.12280719],
       [ 8.7716617 , 12.12550669, 11.77037549,  9.43031107]])

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 What are the Numpy Array Properties?</font></h3>

In [8]:
#First of all lets make an array for ourself
a = np.random.randint(10, size=5)

In [9]:
a.ndim   # dimension info

1

In [10]:
a.shape  # this is also dimension info but it shows that we have 5 number inside

(5,)

In [11]:
a.size   #total number inside of our numpy array

5

In [12]:
a.dtype  #type of our array

dtype('int64')

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 Can i reshape my Numpy array?</font></h3>

In [13]:
#we have one dimension array
np.random.randint(0, 10, size= 9)

array([3, 9, 2, 1, 6, 9, 1, 4, 1])

In [14]:
#We used .reshape(3,3) to reshape it into a 3x3 dimension. Since it has 9 elements, we were able to reshape it to 3x3; if it were 10, 
#it would have thrown an error.
np.random.randint(0, 10, size= 9).reshape(3,3)

array([[3, 2, 0],
       [6, 6, 5],
       [4, 8, 6]])

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 Can i select index that i want in Numpy array?</font></h3>

In [15]:
#we made an array
a = np.random.randint(10, size= 10)

In [16]:
# The assigned value can go to the desired value with the [given number from the list], here we went to the first element.
a[0] #this operation is called index selection

0

In [17]:
#When we say 0:5, it means we went from 0 to 5, including 0 but not including 5. So, it selects the 0th, 1st, 2nd, 3rd, and 4th elements.
a[0:5]

array([0, 4, 6, 7, 6])

In [18]:
a[0] = 999   # With this assignment, we are changing our first value to 999.
a

array([999,   4,   6,   7,   6,   7,   4,   0,   3,   2])

In [19]:
#We created a 3x5 array of random numbers from 0 to 10.
m = np.random.randint(10, size=(3,5))
m

array([[9, 2, 1, 5, 6],
       [0, 1, 9, 5, 5],
       [9, 4, 1, 1, 2]])

In [20]:
#If we want to access the first expression, before the comma represents the rows, and after the comma represents the columns.
m[0,0]

9

In [21]:
m[2,3] # 2nd row, 3rd column"

1

In [22]:
#Numpy is a fixed-type array, so if we assign a float value to this list that we have previously assigned as an integer,
#it will enter as an integer.
m[2,3] = 2.9
m

array([[9, 2, 1, 5, 6],
       [0, 1, 9, 5, 5],
       [9, 4, 1, 2, 2]])

In [23]:
#We said select all rows with :, and we selected the given column with a comma.
m[:,0]

array([9, 0, 9])

In [24]:
#To select the 1st row and all columns, we would write the following expression:
m[1, : ]

array([0, 1, 9, 5, 5])

In [25]:
#We instructed to go from 0 to 2 in rows and from 0 to 3 in columns:
m[0:2, 0:3]

array([[9, 2, 1],
       [0, 1, 9]])

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 What is Fancy index on Numpy?</font></h3>

In [26]:
#We used the 'arange' expression to enter the values that will increase by 3 from 0 to 30 below.
v= np.arange(0, 30, 3)

#We selected the 4th index:
v[4]

12

In [27]:
catch = [1,2,3] # We created a list with values 1-2-3.

#When we put the list into a numpy array, it will return the values 1-2-3 from v, as those values exist in the list.
v[catch]

array([3, 6, 9])

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍Can i do conditional operations in Numpy?</font></h3>

In [28]:
#building array
v=np.array([1,2,3,4,5])

In [29]:
v < 3 #We queried for values less than 3, and it returned true or false

array([ True,  True, False, False, False])

In [30]:
v[v < 3] # When we send this command, it selects the values that are seen as true and does not select the values that are seen as false.

array([1, 2])

In [31]:
v[v > 3] # values greater than 3

array([4, 5])

In [32]:
v[v != 3] # all except 3

array([1, 2, 4, 5])

In [33]:
v[v == 3] # only 3

array([3])

In [34]:
v[v >= 3] # 3 and above

array([3, 4, 5])

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍How can mathematical operations in Numpy ?</font></h3>

In [35]:
#When we say v / 5, it divides all elements by 5 and returns on the screen.
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [36]:
#We multiplied v by 5 and then divided by 10.
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [37]:
#We take the square of v.
v ** 2

array([ 1,  4,  9, 16, 25])

In [38]:
#Subtraction operation from v.
v - 1

array([0, 1, 2, 3, 4])

In [39]:
#np.subtract: subtraction operation
#np.add: addition operation
#np.mean: mean operation
#np.sum: sum operation
#np.min: minimum value
#np.max: maximum value
#np.var: variance
#These are the functions you can use to perform your operations without using the arithmetic operators.

# <p style="border-radius:10px; border:#DEB887 solid; padding:25px; background-color: #FFFAF0; font-size:100%;color:#52017A;text-align:center;"> Pandas</p>

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 What is Pandas and why should i use Pandas ?</font></h3>

### Pandas is the abbreviation for Panel Data. Pandas is a powerful open-source data analysis and manipulation library for Python. It is designed for efficient data analysis and processing. Unlike traditional data structures, Pandas provides DataFrame and Series objects that are ideal for handling structured data and time series data.

* A pandas Series is a one-dimensional data type that contains index information.
* A pandas DataFrame is a two-dimensional data type that contains index information.

In [40]:
#we can import pandas as pd 
import pandas as pd

In [41]:
s = pd.Series([10, 77, 12, 4, 5 ])
type(s)

pandas.core.series.Series

In [42]:
#we can check index, dtype,size,ndim,values methods in one function
def pandascheck(Series):
    print("show index information")
    print(s.index)
    print("-------------------------")
    print("show data type, 'int64'")
    print(s.dtype)   
    print("-------------------------")
    print("show total number of elements")
    print(s.size)    
    print("-------------------------")
    print("show number of dimensions")
    print(s.ndim)    
    print("-------------------------")
    print("access the values inside")
    print(s.values) 

pandascheck(s)

show index information
RangeIndex(start=0, stop=5, step=1)
-------------------------
show data type, 'int64'
int64
-------------------------
show total number of elements
5
-------------------------
show number of dimensions
1
-------------------------
access the values inside
[10 77 12  4  5]


<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍How can i read the data on Pandas ?</font></h3>

In [43]:
# pd.read_csv("path of the csv folder")
# pd.read_excel("path of the excel folder")
# pd.read_json("path of the json folder")

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 Can we use Pandas methods to look at and explain any dataset?</font></h3>

In [44]:
#we are taking df by read_csv method and the path of the our dataset
df = pd.read_csv("/kaggle/input/titanic/train.csv")

In [45]:
df.head().T #quick look at the first 5 indices for a quick glance

0  \
PassengerId                        1   
Survived                           0   
Pclass                             3   
Name         Braund, Mr. Owen Harris   
Sex                             male   
Age                             22.0   
SibSp                              1   
Parch                              0   
Ticket                     A/5 21171   
Fare                            7.25   
Cabin                            NaN   
Embarked                           S   

                                                             1  \
PassengerId                                                  2   
Survived                                                     1   
Pclass                                                       1   
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...   
Sex                                                     female   
Age                                                       38.0   
SibSp                                                        1   
Parch                                                        0   
Ticket                                                PC 17599   
Fare                                                   71.2833   
Cabin                                                      C85   
Embarked                                                     C   

                                  2  \
PassengerId                       3   
Survived                          1   
Pclass                            3   
Name         Heikkinen, Miss. Laina   
Sex                          female   
Age                            26.0   
SibSp                             0   
Parch                             0   
Ticket             STON/O2. 3101282   
Fare                          7.925   
Cabin                           NaN   
Embarked                          S   

                                                        3  \
PassengerId                                             4   
Survived                                                1   
Pclass                                                  1   
Name         Futrelle, Mrs. Jacques Heath (Lily May Peel)   
Sex                                                female   
Age                                                  35.0   
SibSp                                                   1   
Parch                                                   0   
Ticket                                             113803   
Fare                                                 53.1   
Cabin                                                C123   
Embarked                                                S   

                                    4  
PassengerId                         5  
Survived                            0  
Pclass                              3  
Name         Allen, Mr. William Henry  
Sex                              male  
Age                              35.0  
SibSp                               0  
Parch                               0  
Ticket                         373450  
Fare                             8.05  
Cabin                             NaN  
Embarked                            S

In [46]:
df.tail() #last 5 values

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [47]:
df.shape #information about rows and columns

(891, 12)

In [48]:
df.info() #variables, variable types, and if there are any null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [49]:
df.columns #names of the variables

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [50]:
df.index #index information

RangeIndex(start=0, stop=891, step=1)

In [51]:
df.describe().T #summary statistics of numerical information

count        mean         std   min       25%       50%    75%  \
PassengerId  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5   
Survived     891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0   
Pclass       891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0   
Age          714.0   29.699118   14.526497  0.42   20.1250   28.0000   38.0   
SibSp        891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0   
Parch        891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0   
Fare         891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

In [52]:
df.isnull().values.any() #checked for any missing values

True

In [53]:
df.isnull().sum() #checked for the number of null values in each variable

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [54]:
df["Sex"].value_counts() #checked the number of males and females in the sex variable

Sex
male      577
female    314
Name: count, dtype: int64

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 Can i select index that i want with using Pandas?</font></h3>

In [55]:
df[0:13] #goes from 0 to 13

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S

In [56]:
df.drop(0, axis=0).head() #dropped the 0th value, not permanent, but for it to be permanent, you need to write inplace=true

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q

In [57]:
#Convert the variable to index = for example, assigning age to index
df.index = df["Age"]
df.drop("Age", axis=1, inplace=True)
df.head()

PassengerId  Survived  Pclass  \
Age                                   
22.0            1         0       3   
38.0            2         1       1   
26.0            3         1       3   
35.0            4         1       1   
35.0            5         0       3   

                                                   Name     Sex  SibSp  Parch  \
Age                                                                             
22.0                            Braund, Mr. Owen Harris    male      1      0   
38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
26.0                             Heikkinen, Miss. Laina  female      0      0   
35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
35.0                           Allen, Mr. William Henry    male      0      0   

                Ticket     Fare Cabin Embarked  
Age                                             
22.0         A/5 21171   7.2500   NaN        S  
38.0          PC 17599  71.2833   C85        C  
26.0  STON/O2. 3101282   7.9250   NaN        S  
35.0            113803  53.1000  C123        S  
35.0            373450   8.0500   NaN        S

In [58]:
#Convert index to variable
# df.["Age"] = df.index #we put the age, which we made an index, back into the dataframe
df.reset_index(inplace=True) # another way to delete the age variable in the index

In [59]:
#iloc = integer based selection   # selects based on the index
df.iloc[0:3]   # goes from 0 to 3

Age  PassengerId  Survived  Pclass  \
0  22.0            1         0       3   
1  38.0            2         1       1   
2  26.0            3         1       3   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                             Heikkinen, Miss. Laina  female      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S

In [60]:
df.iloc[0,1]

1

In [61]:
#loc: label based selection       # selects columns
df.loc[0:3]

Age  PassengerId  Survived  Pclass  \
0  22.0            1         0       3   
1  38.0            2         1       1   
2  26.0            3         1       3   
3  35.0            4         1       1   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                             Heikkinen, Miss. Laina  female      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S

In [62]:
df.loc[0:3, "Pclass"] #navigated through the Pclass variable from 0 to 3

0    3
1    1
2    3
3    1
Name: Pclass, dtype: int64

In [63]:
df[df["Age"]>50].head()  #people older than 50

Age  PassengerId  Survived  Pclass                              Name  \
6   54.0            7         0       1           McCarthy, Mr. Timothy J   
11  58.0           12         1       1          Bonnell, Miss. Elizabeth   
15  55.0           16         1       2  Hewlett, Mrs. (Mary D Kingcome)    
33  66.0           34         0       2             Wheadon, Mr. Edward H   
54  65.0           55         0       1    Ostby, Mr. Engelhart Cornelius   

       Sex  SibSp  Parch      Ticket     Fare Cabin Embarked  
6     male      0      0       17463  51.8625   E46        S  
11  female      0      0      113783  26.5500  C103        S  
15  female      0      0      248706  16.0000   NaN        S  
33    male      0      0  C.A. 24579  10.5000   NaN        S  
54    male      0      1      113509  61.9792   B30        C

In [64]:
df[df["Age"]>50]["Age"].count()  #number of people older than 50

64

In [65]:
df.loc[df["Age"]>50, ["Age","Pclass"]].head()   #people older than 50 with their classes

Age  Pclass
6   54.0       1
11  58.0       1
15  55.0       2
33  66.0       2
54  65.0       1

In [66]:
#people older than 50 and male
df.loc[(df["Age"]>50) & (df["Sex"] == "male"), ["Age","Pclass"]].head()
#If there are multiple conditions, they should be enclosed in parentheses

Age  Pclass
6   54.0       1
33  66.0       2
54  65.0       1
94  59.0       3
96  71.0       1

In [67]:
df["Age"].mean()  #returns the mean age

29.69911764705882

In [68]:
df.groupby("Sex")["Age"].mean()   #mean of the age variable by gender

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [69]:
df.groupby("Sex").agg({"Age" : ["mean","sum"]})  #mean and sum of age variable by gender, more functions can be used

Age          
             mean       sum
Sex                        
female  27.915709   7286.00
male    30.726645  13919.17

In [70]:
df.groupby("Sex").agg({"Age" : ["mean","sum"],
                       "Survived": "mean"})  #mean and sum of age, and mean of survived variable by gender

Age            Survived
             mean       sum      mean
Sex                                  
female  27.915709   7286.00  0.742038
male    30.726645  13919.17  0.188908

In [71]:
df.groupby(["Sex","Embarked"]).agg({"Age" : "mean",
                                       "Survived": "mean"})         # performed a groupby operation with 2 breakdowns

Age  Survived
Sex    Embarked                     
female C         28.344262  0.876712
       Q         24.291667  0.750000
       S         27.771505  0.689655
male   C         32.998841  0.305263
       Q         30.937500  0.073171
       S         30.291440  0.174603

In [72]:
df.pivot_table("Survived", "Sex",  "Embarked")  # takes the average as default at the intersection of cells

Embarked         C         Q         S
Sex                                   
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [73]:
df.pivot_table("Survived", "Sex",  "Embarked", aggfunc="std")  # took the standard deviation

Embarked         C         Q         S
Sex                                   
female    0.331042  0.439155  0.463778
male      0.462962  0.263652  0.380058

In [74]:
# We divided ages into 0-10, 11-18, 19-25, 26-40, 41-90 and assigned them to a new feature
df["new_age"] = pd.cut(df["Age"],[0,10,18,25,40,90])
# cut = assigns based on the given values, qcut = assigns based on percentile values

In [75]:
df.pivot_table("Survived","Sex","new_age")

new_age   (0, 10]  (10, 18]  (18, 25]  (25, 40]  (40, 90]
Sex                                                      
female   0.612903  0.729730  0.759259  0.802198  0.770833
male     0.575758  0.131579  0.120370  0.220930  0.176471

<div style="border-radius:10px; border:#D0C2F0 solid; padding: 15px; background-color: #FFF0F4; font-size:100%; text-align:left">

<h3 align="left"><font color='#5E5273'>🔍 Can we merge two dataframe with using Pandas?</font></h3>

In [76]:
m = np.random.randint(1,30 , size=(5,3))
df1 = pd.DataFrame(m, columns=["var1","var2","var3"])
df2 = df1+99
# merging df1 and df2
pd.concat([df1,df2])

var1  var2  var3
0    21    17    16
1    19     6    15
2    14    26    23
3    27     9     5
4    20     7    12
0   120   116   115
1   118   105   114
2   113   125   122
3   126   108   104
4   119   106   111

In [77]:
# using ignore index to remove different indices of the two lists and make a single index
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0    21    17    16
1    19     6    15
2    14    26    23
3    27     9     5
4    20     7    12
5   120   116   115
6   118   105   114
7   113   125   122
8   126   108   104
9   119   106   111

In [78]:
df1 = pd.DataFrame({"employees": ["john", "dennis","mark","maria"],
                    "group":  ["accounting","engineering","engineering","hr"]})

df2 = pd.DataFrame({"employees": ["john", "dennis","mark","maria"],
                    "start_date":  [2010,2009,2014,2019]})

# merges two groups based on employees
pd.merge(df1,df2)

employees        group  start_date
0      john   accounting        2010
1    dennis  engineering        2009
2      mark  engineering        2014
3     maria           hr        2019